### ISSUE TITLE
Fail to find latency_predictor.pth.tar

### ISSUE THREAD

**Issue by Ronin3502** [stepbuystep/LightNAS#1]
Hello, thanks for sharing this amazing repository.
I noticed that a MLP is used as the latency predictor in this work, and is directly loaded from "./data/latency_predictor.pth.tar" in the 270th line of search_imagenet.py. But I cannot find the "./data" folder, neither the MLP file "latency_predictor.pth.tar". Could you please provide this file in the repository?

**Comment by stepbuystep** [comment]
Hi, sorry for the late reply. I didn't check github issues that often.

FYI, I have re-constructed the latency predictor and updated it in this repository (see ./data/latency_predictor.pth.tar), which achieves slightly better prediction performance with lower RMSE of 0.028892523102167736 ms.

Feel free to open issues if you still have questions.

**Comment by Ronin3502** [comment]
Got it!!! 
Thanks a lot!
